# @generated by datamodel-codegen:
#   filename:  signalcase.schema.json

from __future__ import annotations

from typing import Annotated, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class StringListItem(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class Conversation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID
    workspace_id: UUID
    source: Annotated[str, Field(min_length=1)]
    external_id: str | None
    text: Annotated[str, Field(max_length=10000, min_length=1)]
    created_at: AwareDatetime


class Document(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID
    workspace_id: UUID
    title: Annotated[str, Field(min_length=1)]
    text: Annotated[str, Field(min_length=1)]
    version: Annotated[str, Field(min_length=1)]


class ExistingIssue(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID
    workspace_id: UUID
    title: Annotated[str, Field(min_length=1)]
    description: Annotated[str, Field(min_length=1)]
    status: Annotated[str, Field(min_length=1)]


class Group(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID
    workspace_id: UUID
    conversation_ids: Annotated[list[UUID], Field(min_length=1)]
    claim: Annotated[str, Field(min_length=1)]
    prerequisites: list[StringListItem]
    unknowns: list[StringListItem]


class Evidence(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID
    job_id: UUID
    workspace_id: UUID
    session_id: UUID | None
    kind: Literal["screenshot", "dom", "action", "document_excerpt", "calculation"]
    created_at: AwareDatetime
    storage_key: Annotated[str, Field(min_length=1)]
    sha256: Annotated[str, Field(pattern="^[a-f0-9]{64}$")]
    mime_type: Annotated[str, Field(min_length=1)]
    summary: Annotated[str, Field(min_length=1)]
    document_id: UUID | None
    quote: str | None


class Event(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID
    job_id: UUID
    workspace_id: UUID
    sequence: Annotated[int, Field(ge=1)]
    created_at: AwareDatetime
    kind: Literal["phase", "action", "observation", "warning", "completion"]
    message: Annotated[str, Field(min_length=1)]
    evidence_ids: list[UUID]


class ExpectedBehavior(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    text: Annotated[str, Field(min_length=1)]
    document_ids: list[UUID]
    assumption: bool


class ActualBehavior(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    text: Annotated[str, Field(min_length=1)]
    evidence_ids: Annotated[list[UUID], Field(min_length=1)]


class InvestigationStep(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    action: Annotated[str, Field(min_length=1)]
    observation: Annotated[str, Field(min_length=1)]
    evidence_ids: Annotated[list[UUID], Field(min_length=1)]


class Attempt(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    session_id: UUID
    result: Annotated[str, Field(min_length=1)]
    evidence_ids: Annotated[list[UUID], Field(min_length=1)]


class DuplicateCandidate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    issue_id: UUID
    reason: Annotated[str, Field(min_length=1)]


class Report(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID
    job_id: UUID
    workspace_id: UUID
    group_id: UUID
    title: Annotated[str, Field(min_length=1)]
    outcome: Literal["reproduced", "not_reproduced", "blocked"]
    interpretation: Literal[
        "observed_defect", "possible_feature_gap", "documented_behavior", "unresolved"
    ]
    source_conversation_ids: Annotated[list[UUID], Field(min_length=1)]
    expected: ExpectedBehavior
    actual: ActualBehavior
    steps: Annotated[list[InvestigationStep], Field(min_length=1)]
    attempts: Annotated[list[Attempt], Field(min_length=1)]
    duplicate_candidates: list[DuplicateCandidate]
    limitations: list[StringListItem]
    proposed_acceptance_checks: list[StringListItem]
    evidence_ids: Annotated[list[UUID], Field(min_length=1)]
    replay_status: Literal["not_generated", "not_run", "passed", "failed"]


class Metrics(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    model_calls: Annotated[int, Field(ge=0)]
    browser_actions: Annotated[int, Field(ge=0)]
    input_tokens: Annotated[int, Field(ge=0)]
    output_tokens: Annotated[int, Field(ge=0)]
    duration_ms: Annotated[int, Field(ge=0)]
    estimated_model_cost_usd_micros: Annotated[int | None, Field(ge=0)]


class Error(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: Literal[
        "INVALID_INPUT",
        "UNAUTHORIZED",
        "NOT_FOUND",
        "WORKSPACE_BUSY",
        "MODEL_UNAVAILABLE",
        "BROWSER_FAILED",
        "DEADLINE_EXCEEDED",
        "WORKER_LOST",
        "STORAGE_FAILED",
        "CONTRACT_INVALID",
    ]
    message: Annotated[str, Field(min_length=1)]
    retryable: bool


class JobInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    conversation_ids: Annotated[list[UUID], Field(min_length=1)]
    max_groups: Annotated[int, Field(ge=1, le=3)]
    seed_version: Annotated[int, Field(ge=1)]


class Job(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID
    workspace_id: UUID
    status: Literal["queued", "running", "completed", "failed", "cancelled"]
    created_at: AwareDatetime
    updated_at: AwareDatetime
    deadline_at: AwareDatetime
    input: JobInput
    group_ids: list[UUID]
    report_ids: list[UUID]
    error: Error | None
    metrics: Metrics


class SignalCaseFixtureBundle(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    contract_version: Literal["1"]
    conversations: Annotated[list[Conversation], Field(max_length=100)]
    documents: list[Document]
    existing_issues: list[ExistingIssue]
    groups: list[Group]
    evidence: list[Evidence]
    events: list[Event]
    reports: list[Report]
    jobs: list[Job]
